name: Pull request pipeline

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Test
              run: |
                  npm ci
                  npm run test
    typecheck:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Typecheck node and web
              run: |
                  npm ci
                  npm run typecheck
    lint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Lint
              run: |
                  npm ci
                  npm run lint
    format:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Check formatting
              run: |
                  npm ci
                  npm run format:check

    release-linux:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3
            - name: Build and release linux
              run: |
                  npm ci
                  npm run release
              env:
                  GH_TOKEN: ${{ secrets.github_token }} 
                  PUBLISH_FOR_PULL_REQUEST: true
