name: Pull request pipeline

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Test
              run: |
                  npm ci
                  npm run test
    typecheck:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Typecheck node and web
              run: |
                  npm ci
                  npm run typecheck
    lint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Lint
              run: |
                  npm ci
                  npm run lint
    format:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Check formatting
              run: |
                  npm ci
                  npm run format:check

    build-linux:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                # GitHub token, automatically provided to the action
                # (No need to define this secret in the repo settings)
                github_token: ${{ secrets.github_token }}

                # If the commit is tagged with a version (e.g. "v1.0.0"),
                # release the app after building
                release: ${{ startsWith(github.ref, 'refs/tags/v') }}